language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: u+Whl1XIVVDjo77UvmvB+wcluMnJMPq++rMHLFL7OH2s102JZay9OnoA4sgVG/ToHuB4Vpg+U//042ixdPwhjyd6o7tehSfQyxcQcvr6t3lUDBRxngQh7ubvaNlHNXXvj2CEbhwGGcfZyJWe/wAtUmOGAyEBqQEHh95K/pfjx5P5xm0KYO8yX3ZQtz+ifu9mvbYjKgQLHpVt61TpZmVgbp/doMZLwgvVY/dagn8ntLhz78eFMMfvqs5bygPG3uVK4N4QLfbHTQ1CPo27dEsg0Kb6koMXOB4/V+uwzsYJk5YhMf5PVBhd7q7XY8yDnmPzw1I971S9ka2BRNf5ioMA1r9qW6It5WySVeUysnDn5iGwaK/wPvN9jAtqAC2s3N6Tn7lW8vfOUI5ivuaF9OshEfBKlxuY67PJP0ZpMN3gDPAYF0iJMe+ddl5O+pt34ihD1I/acRNEuFqtkVi7IPgx7SX6cDmvmOVhGgCNWUZOWwJoT4mw9cTEaysT09J7cThjx3JKqLdD3QKJTt27n7V1kgsI/bb6n36XRWLfoQKGVqUHoGG9PBJPLdHAWZhN3PKGbeJXQMc4WJ+o3LYB/diaZ8I1s8XCaNMGVCq081fHKEdvMPnwfnoTx4j90LeqR4j0lhzkQLGVt8se+lqeIpvNrqdZdQEAp0jq0msGJVDDfbg=
  app: peaceful-fjord-25221